/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type SessionStatus = "closed" | "open";

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface Orders {
  createdAt: Generated<Timestamp>;
  ice: Generated<string>;
  id: string;
  item: string;
  name: string;
  note: Generated<string>;
  price: number | null;
  sessionId: string;
  size: Generated<string>;
  sugar: Generated<string>;
  toppings: Generated<Json>;
  unit: Generated<string>;
}

export interface Sessions {
  createdAt: Generated<Timestamp>;
  id: string;
  participants: Json | null;
  shopId: string;
  shopName: string;
  status: Generated<SessionStatus>;
  title: string;
}

export interface Shops {
  createdAt: Generated<Timestamp>;
  id: string;
  items: Generated<Json>;
  name: string;
  phone: Generated<string>;
  sizes: Generated<Json>;
  toppings: Generated<Json>;
}

export interface Units {
  id: string;
  members: Generated<Json>;
  name: string;
  ord: Generated<number>;
}

export interface DB {
  orders: Orders;
  sessions: Sessions;
  shops: Shops;
  units: Units;
}


// Use these for zod schema enums or other purposes, since the kysely enums are just types
export const SessionStatusArrayValues: [SessionStatus, ...SessionStatus[]] = ["closed","open"];
// Table/column names whose snake_case spelling kysely's default CamelCasePlugin
// cannot recover from the camelCase name used in code (an underscore directly
// before a digit, e.g. reminder_48h_sent ⇄ reminder48hSent). The db helper's
// CamelCasePlugin subclass consults this map so those identifiers work in
// queries. Regenerated on every schema pull.
export const kyselyIdentifierOverrides: Record<string, string> = {};

// Note: kysely maps the table/column/enum names from snake_case to camelCase and PascalCase. When running SQL statements, make sure to use snake_case, but TypeScript code should use camelCase or PascalCase.